"""Generate docs/QA_SCOREBOARD.md — a versioned, regenerable snapshot of per-wolf quality coverage.

Wolf-quality tracking used to live only in a private, unversioned memory note. This replaces it with a
generated artifact derived from FACTS in the repo (each wolf has a prompt? dedicated tests? does the
offline suite pass?), so the scoreboard can't drift from reality — you regenerate it, you don't
hand-edit it. Run: `python scripts/qa_scoreboard.py` (writes the file); pass `--check` to fail if the
committed file is stale (for CI).

It deliberately does NOT try to grade wolf OUTPUT quality (that needs the live-key harness). It tracks
COVERAGE: does each wolf have the assets that let us trust it — a prompt and tests that exercise it.
"""

from __future__ import annotations

import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
PROMPTS = BACKEND / "prompts"
TESTS = BACKEND / "tests"
OUT = BACKEND.parent / "docs" / "QA_SCOREBOARD.md"

# The standing pack. Each wolf's row reports what quality assets back it.
WOLVES = ("scout", "tracker", "sentinel", "howler", "beta", "alpha", "elder", "warden")

# Wolf -> the test files that exercise it (substring match on test file contents). Kept explicit rather
# than guessed so the mapping is auditable.
_WOLF_TEST_HINTS = {
    "scout": ("scout",),
    "tracker": ("merge_attribution", "tracker"),
    "sentinel": ("sentinel",),
    "howler": ("draft", "howler", "offline_hunt"),
    "beta": ("depth_scaling", "beta", "offline_hunt"),
    "alpha": ("alpha",),
    "elder": ("offline_hunt", "elder", "endpoints_v4v5"),
    "warden": ("extra_support_agents", "warden", "healing"),
}


def _has_prompt(wolf: str) -> bool:
    return (PROMPTS / wolf / "v1.md").exists()


def _test_files_for(wolf: str) -> list[str]:
    hits = _WOLF_TEST_HINTS.get(wolf, (wolf,))
    found: list[str] = []
    for path in sorted(TESTS.glob("test_*.py")):
        name = path.stem
        if any(h in name for h in hits):
            found.append(name)
    return found


def render() -> str:
    lines = [
        "# QA scoreboard",
        "",
        "_Generated by `backend/scripts/qa_scoreboard.py` — do not hand-edit; regenerate._",
        "",
        "Coverage of the standing pack: which wolves have a prompt and dedicated test coverage. This",
        "tracks the assets that let us TRUST each wolf; it does not grade live output quality (that",
        "needs the live-key harness, `tests/live/`). The offline suite's own pass/fail is CI's job",
        "(`uv run pytest -q`), not duplicated here.",
        "",
        "| Wolf | Prompt | Test coverage |",
        "| --- | --- | --- |",
    ]
    for wolf in WOLVES:
        prompt = "yes" if _has_prompt(wolf) else "**MISSING**"
        tests = _test_files_for(wolf)
        test_cell = ", ".join(f"`{t}`" for t in tests) if tests else "**none**"
        lines.append(f"| {wolf} | {prompt} | {test_cell} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"{OUT} does not exist — run `python scripts/qa_scoreboard.py` to generate it.")
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current.strip() != content.strip():
            print(f"{OUT} is stale — regenerate with `python scripts/qa_scoreboard.py`.")
            return 1
        print("QA scoreboard is up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
